name: cariera
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  shimmer: ^2.0.0
  shared_preferences: ^2.0.15
  stacked: ^3.0.1
  http: ^0.13.5
  fluttertoast: ^8.1.2
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  intl: ^0.18.0
  flutter_html: ^3.0.0-alpha.6
  pull_to_refresh: ^2.0.0
  google_maps_flutter: ^2.2.2
  cupertino_icons: ^1.0.5
  flutter_svg_provider: ^1.0.3
  url_launcher: ^6.1.11
  # flutter_icons: ^1.1.0
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.2.3
  webview_flutter: ^4.0.1
  share_plus: ^6.3.0
  font_awesome_flutter: ^10.3.0
  change_app_package_name: ^1.1.0
  google_translator: ^1.0.0
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

fonts:
  - family: mplus
    fonts:
      - asset: assets/fonts/font.ttf
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
