// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuQANPo-wvkwSVtzaZvqZrZTAnXE7b1Ak',
    appId: '1:373094573681:web:c515ec1702466a83a6ddd0',
    messagingSenderId: '373094573681',
    projectId: 'arshjobs',
    authDomain: 'arshjobs.firebaseapp.com',
    storageBucket: 'arshjobs.appspot.com',
    measurementId: 'G-HFPG5RHCF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVYl0dE3Mj37dTkUqNj1S_p9fNCAx3Gb0',
    appId: '1:373094573681:android:47ba66e91c8f4bf6a6ddd0',
    messagingSenderId: '373094573681',
    projectId: 'arshjobs',
    storageBucket: 'arshjobs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy20qoZkKX30caFNs1LSxYfVwZmKNVcJI',
    appId: '1:373094573681:ios:2fd22973c7b631efa6ddd0',
    messagingSenderId: '373094573681',
    projectId: 'arshjobs',
    storageBucket: 'arshjobs.appspot.com',
    androidClientId: '373094573681-j2ln8o29uhhe27ij19olq97ubqfb7ekf.apps.googleusercontent.com',
    iosClientId: '373094573681-vocq42g0k2d5u5nf98ovaugib9bfqgoj.apps.googleusercontent.com',
    iosBundleId: 'com.example.cariera',
  );
}
